a  = int(input (" Enter  Number 1 : "))
b  = int(input (" Enter  Number 2 : "))
print(a&b)
print(a|b)
print(a<<b)
print(a>>b)
print(~a)
print(~b)
print(a+b)
print(a-b)
print(a/b)
print(a%b)
print(a//b)
print(a*b)
print(a**b)
print(a == b)
print(a >= b)
print(a <= b)
